### ISSUE TITLE
[question] Toggle options and re-run search in result buffer

### ISSUE THREAD

**Issue by wavexx** [jimporter/urgrep#11]
I've been testing urgrep with ugrep, coming from ripgrep with the `rg` mode.

There are a few things I liked from the rg package, and I wonder if I can achieve something similar in urgrep. I'll describe what I do: I often run a search with something selected while programming, so that searching in a project is usually pretty quick.

After the search I often want to change some settings, then re-run the query. I know I can toggle settings in the prompt, but I'd like to do so after the fact, when I see the results. For example, I'd love to be able to toggle "-w" easily to restrict the current search if I see too many spurious matches. Likewise, toggle search-case, then re-run. If I ran urgrep manually, searching for a regex, I would often want to modify the regex and just re-run the search immediately to see the results (ugrep "-Q" is actually one of the small things that prompted me to compare it to ripgrep). Right now I only see `urgrep-search-again` being bound, which does the job with a prefix arg, but feels kind of slow.

"rg" mode has quick one-keystroke toggles to modify/toggle the option, then re-run the query. Is there already a quick way to do so?

Just mentioning other ideas, "rg" also has an header bar showing the state of the of these toggles. Admittedly, I barely even watched it, but it does provide a convenient way to see the major toggles without parsing the command in the beginning. The only thing I was mostly looking at was the current file type (ug `-t` option).

**Comment by jimporter** [comment]
As you noticed, the way to do this is via `C-u g` and then tweaking the search using the minibuffer commands. There's probably an argument for reducing the number of keystrokes to do this, though I'm not sure I'd want it to be a *single* keystroke. It'd be pretty easy to accidentally hit them (but then on the other hand, it's just as easy to accidentally hit `q` and bury the buffer). Maybe mappings like `M-s c` in the Urgrep buffer would be ok (i.e. you could avoid typing `C-u g` before and `RET` after, so that's 3 or 4 fewer keystrokes depending on how you want to count things).

**Comment by wavexx** [comment]
Thanks for the answer!

Accidental typing wasn't an issue with the rg package. TBH, with either ripgrep and ugrep search is usually so fast, the main issue was accumulation of results in the buffer, slowing emacs down :(

I'll try/experiment a bit.

**Comment by jimporter** [comment]
I think it makes sense to keep this open, since I want to at least think about what (if anything) to do here. Making it easier to edit your search parameters is a pretty reasonable feature to add.

As an aside, while it doesn't help with Emacs slowness, the latest dev version of Urgrep now supports `outline-minor-mode`, so that's another way of managing overwhelming results: you can collapse all the sections and then only expand the files you want to look at results for.

(And for searches with many, many results, I do wonder if some of the slowness is due to the regexes Urgrep uses to fontify the results. Maybe simplifying those regexes or doing more work in `urgrep-filter` would help performance...)

**Comment by wavexx** [comment]
I was looking at introducing a new custom toggle for "ignore-files". Specifically, I want to be able to toggle the presence of "--no-ignore-files". Right now we have ignore-hidden, which I never used in the past, whereas what usually happens to me is that I have a default set of ignore rules for a project that I occasionally want to exclude.

I don't see an easy way to append a new flag or flags programmatically to the current tool, sort of "extra-flags", to implement this on top of the current interface.

**Comment by jimporter** [comment]
@wavexx I've started implementing something for this by adding single-key bindings for expanding context in the results buffer (`C`, `B`, `A`). I'll keep adding more commands like this over the next few days, but if you're impatient (or just want a toggle for something unusual), you can write your own commands based on this commit: 92e3fc9141f55bed40f0e0e3e5d5476a44dec8fd
